name: bemba_lingo


version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

assets:
  - assets/

dependencies:
  flutter: 
    sdk: flutter
  http: ^0.13.3
  
  



  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  avatar_glow: ^2.0.2
  record_mp3: ^3.0.0
  permission_handler: ^11.0.1
  google_fonts: ^4.0.4
  loading_animation_widget: ^1.2.0+4

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0



# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
